<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Resursbank\Core\ViewModel\Error;

/** @var Template $block */
/** @var Error $viewModel */

if (isset($block)) {
    /** @noinspection PhpPossiblePolymorphicInvocationInspection */
    $viewModel = $block->getViewModel();
}

?>

<?php // Didn't combine if-blocks because PHPStan will complain unnecessarily. ?>
<?php if (isset($viewModel)): ?>
    <?php if ($viewModel->paymentFailed()): ?>
        <script>
            require(['Magento_Ui/js/model/messageList', 'mage/translate'], function(messages, $t) {
                messages.addErrorMessage({
                    'message':
                        $t('The payment failed. Please confirm the cart content and try a different payment method')
                })
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
