<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Resursbank\Core\Block\Adminhtml\System\Config\GetStores;

/** @var GetStores $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */

$widget = $block->getWidget();

if ($widget !== '') {
    /* @noEscape */
    echo $secureRenderer->renderTag(
        tagName: 'script',
        attributes: [],
        content: $widget,
        textContent: false
    );
}
?>
<script>
    function getResursBankFetchStoresUrl() {
        let urls = [];

        <?php foreach ($block->getUrls() as $api => $url): ?>
        urls['<?= $escaper->escapeJs(string: $api) ?>'] = '<?= $escaper->escapeJs(string: $url) ?>';
        <?php endforeach; ?>

        let selectedApi = document.getElementById('payment_other_resursbank_section_api_flow').value;

        return urls[selectedApi] ?? '';
    }

    function getResursBankClientId() {
        let clientId;

        let flow = document.getElementById('payment_other_resursbank_section_api_flow').value;
        let environment = document.getElementById('payment_other_resursbank_section_api_environment').value;
        let elementId = 'payment_other_resursbank_section_api_client_id_' +
            flow + '_' + environment;

        clientId = document.getElementById(elementId).value;

        return clientId;
    }

    function getResursBankClientSecret() {
        let clientSecret;

        let flow = document.getElementById('payment_other_resursbank_section_api_flow').value;
        let environment = document.getElementById('payment_other_resursbank_section_api_environment').value;
        let elementId = 'payment_other_resursbank_section_api_client_secret_' +
            flow + '_' + environment;

        clientSecret = document.getElementById(elementId).value;

        return clientSecret;
    }

    /* This is to translate our message in view/adminhtml/web/js/system/stores.js
       since ECom translations are not available to the frontend i18n package. */
    const resursbankPleaseSelectStoreMsg = '<?= $escaper->escapeHtml(data: __('rb-please-select-store')) ?>';
</script>
